fix

diff --git a/.github/workflows/auto-commit-build.yml b/.github/workflows/auto-commit-build.yml
--- a/.github/workflows/auto-commit-build.yml
+++ b/.github/workflows/auto-commit-build.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
-
 name: auto-commit-build
 
 on:
@@ -11,19 +8,30 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        node-version: [16.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
     - uses: actions/checkout@v2
     - name: Build dist
       run: |
         yarn
-        yarn build
-        echo "built"
-        ls dist
+        yarn test
+        if [ $? == 0 ]; then
+          echo "Yarn test passed";
+          echo "Building package.."
+
+          yarn build
+
+          if [ $? != 0 ]; then
+            echo "Yarn build failed"
+            echo "Aborting"
+            exit 1
+          fi
+
+          echo "Contents of dist"
+          ls dist
+        else
+          echo "Yarn test failed"
+          echo "Aborting"
+          exit 1
+        fi
